### ISSUE TITLE
Keep root directory clean

### ISSUE THREAD

**Issue by soumyaray** [Mew-Traveler/mew-api#1]
Move files into proper folders:
- api_explor.rb: into lib?
- response.yml: into spec/fixtures
- results.yml: into spec/fixtures

**Comment by Tailcloud** [comment]
@soumyaray  I think we move them to the proper folder? can you.....check it for us again...Thanks very much.

**Comment by soumyaray** [comment]
Looks good :)

One suggestion:  in future, when responding to an issue with a commit, please put a link to that commit (or branch) in your comment.  I didn't know which branch to check at first!
