### ISSUE TITLE
rename files

### ISSUE THREAD

**Issue by soumyaray** [Mew-Traveler/mew-api#2]
Give intuitive file names:
- spec/load_spec --?--> spec/airbnb_spec (or something like that)

why is 'load' in so many file names?

**Comment by Tailcloud** [comment]
@soumyaray  and I change load_spec to overallapi_spec in temp. can you check it for us too? THX~

**Comment by soumyaray** [comment]
sounds ok!  In future, you might want to break it into multiple specs to test different parts of the API.  I'll show examples in class :)
