### ISSUE TITLE
Isolate HTTP and library code

### ISSUE THREAD

**Issue by soumyaray** [Mew-Traveler/mew-api#3]
Need to move HTTP/json calls into a special class (airbnb_api.rb ?), and then use your other classes to simply call that api class.  See our class notes about this.

**Comment by Tailcloud** [comment]
@soumyaray  I might fix this issue, can you check it for us? THX 💯

**Comment by soumyaray** [comment]
That's exactly what I wanted!  Now, if they URLs of the API for Airbnb changes, or they start returning something other than JSON, you only have to change that one file that talks to the API.  I'll show even deeper examples of isolation in the coming class :)
